name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      shell: bash
      run:  |
            ls
            mkdir build
            cd build
            pip3 install wheel
            pip3 install setuptools
            pip3 install conan
            export PATH=$PATH:/home/runner/.local/bin
            export CXX=g++-9
            conan config init
            conan profile update settings.compiler.libcxx=libstdc++11 default
            conan install ..
            cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
            cmake --build . --config $BUILD_TYPE
